# Generated by Django 3.2 on 2024-02-29 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0014_alter_watermark_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('production_date', models.DateField()),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_batch', to='photologue.gallery')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
